### PR TITLE
Reduced dependencies and copied signer from aws-amplify

### LINKED ISSUE #29: 280 MB of dependencies for this?
### Describe the bug

Create an empty node project. Install this npm package. Several minutes later your node_modules folder takes up 200+ MB.

Is that really necessary? Why does a JavaScript auth helper pull in _all of React Native_ (59.6 MB)? I'm not using any flavor of React.

Also there's warnings about 9 deprecated packages this library depends on.

Please clean up your dependencies!

### Expected Behavior

This dependency should not increase the size of my docker image by 40% for the sake of `withAPIKey(...).getLocationClientConfig()`.

### Current Behavior

My node_modules folder went from 100 MB to 300 MB just from this one package!

### Reproduction Steps

Create an empy node project. Install this npm package. Several minutes later your node_modules folder takes up 200+ MB.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### Environment details (OS name and version, browser, etc.)

Irrelevant

### PR DESCRIPTION
**Pull request by cgalvan**
_Issue #, if available:_

Fixes #29 

_Description of changes:_

The purpose of this change was to reduce the size of our dependencies. In #29 it was uncovered that our total dependency size was ~280MB. A lot of this came from `@aws-amplify/core`, which we were using for our sigv4 signing.

Prior to this change, our dependencies were:
```
"@aws-amplify/core": "^5.5.0",
"@aws-sdk/client-location": "^3.359.0",
"@aws-sdk/credential-providers": "^3.359.0",
"@aws-sdk/types": "^3.347.0"
```

I updated these to the latest versions, and there had been a lot of dependency trimming, but there was a major API breakage in `@aws-amplify/core`. They no longer export the `Signer`, and are intending to deprecate it in favor of another internal signing library (that the `Signer` currently calls internally), which is also not exported:

https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/clients/middleware/signing/signer/signatureV4

So, I have copied over the `Signer` class and left a long comment detailing this move.

This changes our dependencies to:
```
"@aws-crypto/sha256-js": "^5.2.0",
"@aws-sdk/client-location": "^3.549.0",
"@aws-sdk/credential-providers": "^3.549.0",
"@aws-sdk/types": "^3.535.0",
"@smithy/util-hex-encoding": "^2.0.0"
```

Installing these dependencies in an empty repo results in only 19MB!

_Testing:_

Updated the unit tests to test the output of the signer. Ran unit tests and all pass.

```
> npm test
 PASS  src/index.test.ts
 PASS  src/cognito/index.test.ts
 PASS  src/apikey/index.test.ts
-------------|---------|----------|---------|---------|-------------------
File         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-------------|---------|----------|---------|---------|-------------------
All files    |   97.47 |    69.56 |   94.44 |   98.27 |
 src         |     100 |      100 |     100 |     100 |
  index.ts   |     100 |      100 |     100 |     100 |
 src/apikey  |     100 |      100 |     100 |     100 |
  index.ts   |     100 |      100 |     100 |     100 |
 src/cognito |     100 |      100 |     100 |     100 |
  index.ts   |     100 |      100 |     100 |     100 |
 src/utils   |   96.73 |    58.82 |    92.3 |   97.75 |
  signer.ts  |   96.73 |    58.82 |    92.3 |   97.75 | 321,349
-------------|---------|----------|---------|---------|-------------------

Test Suites: 3 passed, 3 total
Tests:       19 passed, 19 total
Snapshots:   0 total
Time:        0.953 s, estimated 1 s
Ran all test suites.
```

Also ran `npm run build` and used the output in a simple local test app with both API key and cognito and verified a map is loaded properly.

### CODE REVIEW

File: src/utils/signer.ts [hunk 1]
```diff
@@ -0,0 +1,440 @@
+/*
+ * This is a copied and modified file from https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/Signer/Signer.ts
```
Comment (imraymondlee) [inline src/utils/signer.ts:2]: Would it worth specifying which point in the commit history of these files that it was copied from? That way we can reference back to it if there are ever changes made by Amplify.

File: src/utils/signer.ts [hunk 2]
```diff
@@ -0,0 +1,440 @@
...
+ * as well as several classes from https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/clients/middleware/signing/signer/signatureV4
```
Comment (imraymondlee) [inline src/utils/signer.ts:3]: I'm assuming these are TOKEN_QUERY_PARAM, presignUrl, signRequest. Is that correct?

Comment (imraymondlee) [reply src/utils/signer.ts:3]: Actually... I don't see signRequest copied over, which I do see it imported in https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/Signer/Signer.ts#L7. Is it needed?

**Review by juaneslucero — DISMISSED** [review]

File: src/utils/signer.ts (hunk 2 above)
Comment (cgalvan) [reply src/utils/signer.ts:3]: `signRequest` is only needed for `Signer.sign`, so I didn't copy it over since I only included the `Signer.signUrl` method.

File: src/utils/signer.ts (hunk 1 above)
Comment (cgalvan) [reply src/utils/signer.ts:2]: Good call! I'll include the actual commit I copied this from.

**Review by imraymondlee — APPROVED** [review]

**Review by juaneslucero — APPROVED** [review]
